name: Azure Files PoC Terraform Validation

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/validation/**'
      - '.github/workflows/azure-terraform-validation.yml'

jobs:
  validate-terraform:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./terraform/validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_dev_location: ${{ vars.AZURE_LOCATION || 'East US' }}
          TF_VAR_environment: "dev"
          TF_VAR_dev_resource_group: ${{ secrets.DEV_RESOURCE_GROUP_NAME }}
          TF_VAR_dev_vnet_name: ${{ secrets.DEV_VNET_NAME }}
          TF_VAR_dev_vnet_resource_group: ${{ secrets.DEV_VNET_RESOURCE_GROUP }}
          TF_VAR_dev_subscription_name: ${{ secrets.AZURE_SUBSCRIPTION_NAME }}
          TF_VAR_dev_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_dev_storage_account_name: ${{ vars.DEV_STORAGE_ACCOUNT_NAME || 'stexampledev01' }}
          TF_VAR_dev_file_share_name: ${{ vars.DEV_FILE_SHARE_NAME || 'fspoc' }}
          TF_VAR_dev_file_share_quota_gb: ${{ vars.DEV_FILE_SHARE_QUOTA_GB || 5 }}
          TF_VAR_dev_vnet_id: ${{ secrets.DEV_VNET_ID }}
          TF_VAR_common_tags: '{ "ManagedBy" = "GitHubActions", "Project" = "AzureFilesPoC" }'

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve -no-color
        env:
          TF_VAR_dev_location: ${{ vars.AZURE_LOCATION || 'East US' }}
          TF_VAR_environment: "dev"
          TF_VAR_dev_resource_group: ${{ secrets.DEV_RESOURCE_GROUP_NAME }}
          TF_VAR_dev_vnet_name: ${{ secrets.DEV_VNET_NAME }}
          TF_VAR_dev_vnet_resource_group: ${{ secrets.DEV_VNET_RESOURCE_GROUP }}
          TF_VAR_dev_subscription_name: ${{ secrets.AZURE_SUBSCRIPTION_NAME }}
          TF_VAR_dev_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_dev_storage_account_name: ${{ vars.DEV_STORAGE_ACCOUNT_NAME || 'stexampledev01' }}
          TF_VAR_dev_file_share_name: ${{ vars.DEV_FILE_SHARE_NAME || 'fspoc' }}
          TF_VAR_dev_file_share_quota_gb: ${{ vars.DEV_FILE_SHARE_QUOTA_GB || 5 }}
          TF_VAR_dev_vnet_id: ${{ secrets.DEV_VNET_ID }}
          TF_VAR_common_tags: '{ "ManagedBy" = "GitHubActions", "Project" = "AzureFilesPoC" }'

      - name: Terraform Output
        run: terraform output
