name: Azure Files PoC Deploy Infrastructure

# This workflow is the main entry point for Terraform infrastructure deployments.
# It uses the reusable terraform-common.yml workflow for the actual Terraform operations.
#
# Related workflows:
# - terraform-common.yml: Reusable workflow with all Terraform steps (init, plan, apply)
# - terraform-validation.yml: Separate workflow for validating the overall CI/CD process
# - azure-login-validation.yml: Simple workflow for validating Azure authentication

permissions:
  id-token: write # Required for OpenID Connect (OIDC) authentication with Azure
  contents: read  # Required to checkout the repository content

on:
  # Manual trigger with environment selection
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      plan_only:
        description: 'Only run plan (no apply)'
        required: true
        type: boolean
        default: true

  # Pull request automation - run Terraform plan on PRs
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

#========================================================================================
# CHANGE 1: ADDED CONCURRENCY BLOCK
# This prevents multiple workflow runs for the same branch/PR from executing at the
# same time, which is the primary cause of "state is already locked" errors in CI/CD.
#========================================================================================
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Primary Terraform workflow that uses the common reusable workflow
  # This job is configured to run when the workflow is manually dispatched.
  # The 'environment' and 'plan_only' inputs will be passed to the reusable workflow.
  deploy-infrastructure:
    uses: ./.github/workflows/terraform-common.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      plan_only: ${{ github.event.inputs.plan_only || true }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Standalone job for 'dev' environment Terraform operations.
  # This job will run on pull requests (if paths match) and also when
  # the workflow is dispatched, unless specifically excluded by conditionals.
  # It's good for focused debugging or specific environment deployments.
  terraform-dev:
    runs-on: ubuntu-latest
    # Define environment variables for Terraform AzureRM provider.
    # ARM_USE_OIDC is crucial for telling the Azurerm provider to use OIDC authentication.
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Verify GitHub Vars (Debug Step)
        run: |
          echo "Checking GitHub Variables for dev environment:"
          echo "DEV_SUBNET_ADDRESS_PREFIXES: ${{ vars.DEV_SUBNET_ADDRESS_PREFIXES }}"
          echo "DEV_VNET_DNS_SERVERS: ${{ vars.DEV_VNET_DNS_SERVERS }}"
          echo "DEV_COMMON_TAGS: ${{ vars.DEV_COMMON_TAGS }}"
          # etc...

      - name: Create terraform/environments/dev directory if it doesn't exist
        run: mkdir -p terraform/environments/dev

      #========================================================================================
      # CHANGE 2: ROBUST terraform.tfvars GENERATION
      # This uses the toJson() function to ensure that lists and maps are formatted correctly
      # for Terraform. This requires the corresponding GitHub variables to be stored in valid JSON.
      #========================================================================================
      - name: Generate terraform.tfvars for dev
        run: |
          cat <<EOF > terraform/environments/dev/terraform.tfvars
          azure_location              = "${{ vars.AZURE_LOCATION }}"
          dev_resource_group          = "${{ vars.DEV_RESOURCE_GROUP }}"
          dev_storage_account_name    = "${{ vars.DEV_STORAGE_ACCOUNT_NAME }}"
          dev_file_share_name         = "${{ vars.DEV_FILE_SHARE_NAME }}"
          dev_file_share_quota_gb     = ${{ vars.DEV_FILE_SHARE_QUOTA_GB }}
          dev_network_security_group  = "${{ vars.DEV_NETWORK_SECURITY_GROUP }}"
          dev_resource_id             = "${{ vars.DEV_RESOURCE_ID }}"
          dev_subnet_name             = "${{ vars.DEV_SUBNET_NAME }}"
          dev_vnet_id                 = "${{ vars.DEV_VNET_ID }}"
          dev_vnet_name               = "${{ vars.DEV_VNET_NAME }}"
          dev_vnet_resource_group     = "${{ vars.DEV_VNET_RESOURCE_GROUP }}"
          
          # Use toJson() for lists and maps.
          # NOTE: The corresponding GitHub variables MUST be stored in valid JSON format.
          # e.g., ["10.0.0.1"] or {"key": "value"}
          dev_subnet_address_prefixes = ${{ toJson(vars.DEV_SUBNET_ADDRESS_PREFIXES) }}
          dev_vnet_address_space      = ${{ toJson(vars.DEV_VNET_ADDRESS_SPACE) }}
          dev_vnet_dns_servers        = ${{ toJson(vars.DEV_VNET_DNS_SERVERS) }}
          common_tags                 = ${{ toJson(vars.DEV_COMMON_TAGS) }}
          EOF

      - name: Display Generated terraform.tfvars (Debug Step)
        run: |
          echo "Content of terraform/environments/dev/terraform.tfvars:"
          cat terraform/environments/dev/terraform.tfvars || echo "File not found or empty."

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init -backend-config="resource_group_name=${{ vars.DEV_TFSTATE_RG }}" -backend-config="storage_account_name=${{ vars.DEV_TFSTATE_SA }}" -backend-config="container_name=${{ vars.DEV_TFSTATE_CONTAINER }}" -backend-config="key=dev.terraform.tfstate"

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Example condition
      #   working-directory: terraform/environments/dev
      #   run: terraform apply -auto-approve tfplan