# In /.github/workflows/main.yml
name: Azure Files PoC Deploy Infrastructure

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      plan_only:
        description: 'Only run plan (no apply)'
        required: true
        type: boolean
        default: true
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This job seems to be for a different deployment strategy or environment.
  # We are focusing on the 'terraform-dev' job for now.
  # deploy-infrastructure:
  #   uses: ./.github/workflows/terraform-common.yml
  #   # ...

  terraform-dev:
    name: 'Terraform Deploy to Dev (Trusted Services Test)'
    runs-on: ubuntu-latest
    environment: dev # Ensures correct GitHub Environment variables/secrets are used
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      # The "Get GitHub Runner Public IP" step is NOT needed for this test.
      # - name: Get GitHub Runner Public IP
      #   id: ip
      #   uses: haythem/public-ip@v1.3

      - name: Display Module Content (Debug Step)
        run: |
          echo "--- Content of terraform/modules/storage/account/main.tf (for Trusted Services Test) ---"
          cat terraform/modules/storage/account/main.tf
          echo "---------------------------------------------------------------------------------------"

      - name: Generate terraform.tfvars for dev
        run: |
          # Ensure this script does not try to set 'allowed_ip_rules' if it was previously there.
          cat <<EOF > terraform/environments/dev/terraform.tfvars
          azure_location              = "${{ vars.AZURE_LOCATION }}"
          dev_resource_group          = "${{ vars.DEV_RESOURCE_GROUP }}"
          dev_resource_group_b          = "${{ vars.DEV_RESOURCE_GROUP_B }}"
          dev_storage_account_name    = "${{ vars.DEV_STORAGE_ACCOUNT_NAME }}"
          dev_file_share_name         = "${{ vars.DEV_FILE_SHARE_NAME }}"
          dev_file_share_quota_gb     = ${{ vars.DEV_FILE_SHARE_QUOTA_GB }}
          dev_network_security_group  = "${{ vars.DEV_NETWORK_SECURITY_GROUP }}"
          dev_resource_id             = "${{ vars.DEV_RESOURCE_ID }}"
          dev_subnet_name             = "${{ vars.DEV_SUBNET_NAME }}"
          dev_vnet_id                 = "${{ vars.DEV_VNET_ID }}"
          dev_vnet_name               = "${{ vars.DEV_VNET_NAME }}"
          dev_vnet_resource_group     = "${{ vars.DEV_VNET_RESOURCE_GROUP }}"
          dev_subnet_address_prefixes = ${{ vars.DEV_SUBNET_ADDRESS_PREFIXES }}
          dev_vnet_address_space      = ${{ vars.DEV_VNET_ADDRESS_SPACE }}
          dev_vnet_dns_servers        = ${{ vars.DEV_VNET_DNS_SERVERS }}
          dev_dns_servers             = ${{ vars.DEV_DNS_SERVERS }}
          common_tags                 = ${{ vars.DEV_COMMON_TAGS }}
          EOF

      - name: Display Generated terraform.tfvars (Debug Step)
        run: |
          echo "Content of the generated terraform/environments/dev/terraform.tfvars:"
          cat terraform/environments/dev/terraform.tfvars || echo "File not found or empty."

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init -backend-config="resource_group_name=${{ vars.DEV_TFSTATE_RG }}" -backend-config="storage_account_name=${{ vars.DEV_TFSTATE_SA }}" -backend-config="container_name=${{ vars.DEV_TFSTATE_CONTAINER }}" -backend-config="key=dev.terraform.tfstate"

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate

      # MODIFIED for this test: The terraform plan command is simplified and does not pass '-var="allowed_ip_rules=[...]"'
      - name: Terraform Plan
        id: plan
        working-directory: terraform/environments/dev
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.plan_only == 'false')
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve tfplan