on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: dev
      plan_only:
        required: false
        type: boolean
        default: true
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-login debug
        run: echo "About to run Azure Login"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Post-login debug
        run: echo "Azure Login complete"

      - name: Show Azure Account Info
        run: az account show

      - name: Generate terraform.tfvars for dev
        run: |
          cat <<EOF > terraform/environments/dev/terraform.tfvars
          azure_location = "${{ vars.AZURE_LOCATION }}"
          dev_resource_group = "${{ vars.DEV_RESOURCE_GROUP }}"
          dev_storage_account_name = "${{ vars.DEV_STORAGE_ACCOUNT_NAME }}"
          dev_file_share_name = "${{ vars.DEV_FILE_SHARE_NAME }}"
          dev_file_share_quota_gb = ${{ vars.DEV_FILE_SHARE_QUOTA_GB }}
          dev_dns_servers = ${{ vars.DEV_DNS_SERVERS }}
          # Add any other required variables for your modules here
          EOF

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -var-file=terraform.tfvars

      # Uncomment to enable apply
      # - name: Terraform Apply
      #   working-directory: terraform/environments/dev
      #   run: terraform apply -auto-approve -var-file=terraform.tfvars